# Generated by Django 4.2 on 2023-04-17 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0004_alter_app_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.CharField(default='', max_length=20),
        ),
    ]
