# Generated by Django 4.2 on 2023-04-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0007_alter_app_user_email_alter_app_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='password',
            field=models.TextField(default='', max_length=255),
        ),
    ]
