# Generated by Django 4.2 on 2023-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0008_alter_app_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='password',
            field=models.TextField(default=''),
        ),
    ]
