# Generated by Django 4.2 on 2023-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0009_alter_app_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
