# Generated by Django 4.2 on 2023-04-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0010_alter_app_user_email_alter_app_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
