# Generated by Django 4.2 on 2023-04-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0011_alter_app_user_email_alter_app_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_user',
            name='osrs_profile',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
