# Generated by Django 4.2 on 2023-04-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0012_app_user_osrs_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
