# Generated by Django 4.2 on 2023-04-26 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0015_timers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Timers',
            new_name='Timer',
        ),
    ]
