# Generated by Django 4.2 on 2023-04-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmo_tracker_app', '0016_rename_timers_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timer',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='timer',
            name='start_time',
        ),
        migrations.AddField(
            model_name='timer',
            name='hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timer',
            name='mins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timer',
            name='sec',
            field=models.IntegerField(default=0),
        ),
    ]
